server:
  port: 5000
spring:
  application:
    name: EMS
  datasource:
    url: jdbc:mysql://localhost:3306/EMS
    password: P@$$w0rd1..
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update